domain_path: E:\intelFPGA\FPGA-Learn\Code\UART_IO\platform_uart\export\platform_uart\sw\standalone_microblaze_mcs_0_microblaze_I
app_src_dir: H:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\peripheral_tests
template: peripheral_tests
lang: c
