domain_path: E:\intelFPGA\FPGA-Learn\Code\UART\platform_uart\export\platform_uart\sw\standalone_microblaze_mcs_0_microblaze_I
app_src_dir: H:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
